### CONTAINERS ###

nginx:
  repository: docker-registry.jx.dev.friendzone.bot/bakuutin/fbftp
  tag: 0.0.4
  worker_connections: 10240
  worker_processes: 2

sftp:
  repository: "atmoz/sftp"
  tag: "alpine"
  port: 22

  ## sftp.user SFTP User
  # user: user

  ## sftp.password SFTP Password
  # password: password


resources:
  requests:
    ## resources.requests.cpu CPU resource requests
    cpu: 1m

    ## resources.requests.memory Memory resource requests
    memory: 1Mi

  limits:
  # resources.limits.cpu CPU resource limits
    cpu: 1000m

  # resources.limits.memory Memory resource limits
    memory: 1024Mi


### STORAGE ###

persistence:
  ## persistence.enabled Enables persistent volume - PV provisioner support necessary
  enabled: true

  ## persistence.keep Keep persistent volume after helm delete
  keep: false

  ## persistence.accessMode PVC Access Mode
  accessMode: ReadWriteOnce

  ## persistence.size PVC Size
  size: 5Gi


### NETWORKING ###

service:
  ## service.type Changes to ClusterIP automatically if ingress enabled
  type: LoadBalancer

  ## service.HTTPPort Port to advertise the main web service in LoadBalancer mode
  HTTPPort: 80
