apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lamp.fullname" . }}-nginx
  labels:
    app: {{ template "lamp.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
{{ (.Files.Glob "files/nginx.conf").AsConfig | indent 2 }}
