apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "lamp.fullname" . }}
  labels:
    app: {{ template "lamp.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "lamp.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: sftp
        image: "{{ .Values.sftp.repository }}:{{ .Values.sftp.tag }}"
        command: [/bin/bash, -c, "bash /entrypoint $SFTP_USER:$SFTP_PASSWORD:33:33"]
        ports:
        - containerPort: 22
        env:
        - name: SFTP_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "lamp.fullname" . }}
              key: sftp-user
        - name: SFTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "lamp.fullname" . }}
              key: sftp-password
        volumeMounts:
        - name: webroot
          mountPath: /home/{{ .Values.sftp.user }}/web/
        resources:
{{ toYaml .Values.resources | indent 12 }}
      - name: nginx
        image: "{{ .Values.nginx.repository }}:{{ .Values.nginx.tag }}"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx
          readOnly: true
          name: nginx-conf
        - name: webroot
          mountPath: /srv/webroot/
        resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: nginx-conf
        configMap:
          name: "{{ template "lamp.fullname" . }}-nginx"
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: webroot
        persistentVolumeClaim:
          claimName: {{ template "lamp.fullname" . }}
