apiVersion: v1
kind: Service
metadata:
  name: {{ template "lamp.fullname" . }}
  labels:
    app: {{ template "lamp.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.HTTPPort }}
    targetPort: 80
    protocol: TCP
    name: http
  - port: {{ .Values.sftp.port }}
    targetPort: 22
    protocol: TCP
    name: sftp
  selector:
    app: {{ template "lamp.name" . }}
    release: {{ .Release.Name }}
