kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fbftp.fullname" . }}
  labels:
    app: {{ template "fbftp.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
